
tasks:
  - init: pnpm install && pnpm run build
    command: pnpm run dev
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - rvest.vs-code-prettier-eslint
    - bradlc.vscode-tailwindcss
    - GitHub.copilot
